version: '3.8'

services:
    db:
        image: mysql
        container_name: db_docker_symfony
        restart: always
        volumes:
            - ./database:/var/lib/mysql
        networks:
            - dev
        environment:
            MYSQL_ROOT_PASSWORD: davy

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: always
        networks:
            - dev
        depends_on:
            - db
        environment:
            PMA_HOST: db
        ports:
            - 8888:80

    www:
        build: .
        container_name: www_docker_symfony
        restart: always
        volumes:
            - ./vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        networks:
            - dev
        ports:
            - 5555:80

networks:
    dev:
 
volumes:
    database: